vulnerable/urls.py
from django.contrib import admin
from django.urls import path
from camara import views
from django.conf  import settings
from django.conf.urls.static import  static
from clinico import views as viewsClinico
from mecanicosPacientes import views as viewsmecanicosPacientes


urlpatterns = [
    path('admin/', admin.site.urls),
    path('acceso/', views.acceso),
    path('menu/', views.menu),
    path('camara/', views.camara),
    path('leeAudio/', views.leeAudio),
    path('reconocerAudio/', views.reconocerAudio),
    path('reproduceAudio/', views.reproduceAudio),
    path('historiaView/', viewsClinico.nuevoView.as_view()),
    path('historia1View/', viewsClinico.historia1View),
    path('historiaExamenesView/', viewsClinico.historiaExamenesView),
    path('consecutivo_folios/', viewsClinico.consecutivo_folios),
    path('buscaExamenes/', viewsClinico.buscaExamenes),
    path('motivoSeñas/', viewsClinico.motivoSeñas),
    path('subjetivoSeñas/', viewsClinico.subjetivoSeñas),
    path('motivoInvidente/', viewsClinico.motivoInvidente),
    path('resMotivoInvidente/', viewsClinico.resMotivoInvidente),
    path('prueba/', viewsClinico.prueba),
    path('manejoLuz/', viewsmecanicosPacientes.manejoLuz),
    path('prenderLuz/', viewsmecanicosPacientes.prenderLuz),
    path('apagarLuz/', viewsmecanicosPacientes.apagarLuz),







]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

clinico/forms.py
from django import forms
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Historia, Especialidades, Medicos
from usuarios.models import TiposDocumento, Usuarios
from clinico.models import TiposExamen, Examenes, HistoriaExamenes
import django.core.validators
import django.core.exceptions
from django.core.exceptions import ValidationError




class historiaForm(forms.ModelForm):

    class Meta:
        model = Historia

        id_tipo_doc = forms.ModelChoiceField(queryset=TiposDocumento.objects.all())
        documento = forms.IntegerField(label='No Documento')
        folio = forms.IntegerField(label='No Folio', disabled=True, initial=0)
        fecha = forms.DateTimeField()

        id_especialidad = forms.ModelChoiceField(queryset=Especialidades.objects.all())
        id_medico = forms.ModelChoiceField(queryset=Medicos.objects.all())
       # folio = forms.IntegerField(label='No Folio',  initial=0)
        estado_folio = forms.CharField(label='Estado del Folio', disabled=True, initial='A', max_length=1)

        fields = '__all__'

        widgets = {
            'motivo':    forms.Textarea(attrs={'class': 'form-control', 'width': "100%", 'cols': "40", 'rows': "4", 'placeholder': "Motivo"}),
            'subjetivo': forms.Textarea(attrs={'class': 'form-control', 'width': "100%", 'cols': "40", 'rows': "4", 'placeholder': "Subjetivo"}),
            'objetivo':  forms.Textarea(attrs={'class': 'form-control', 'width': "100%", 'cols': "40", 'rows': "4", 'placeholder': "Objetivo"}),
            'analisis':  forms.Textarea(attrs={'class': 'form-control', 'width': "100%", 'cols': "40", 'rows': "4", 'placeholder': "Analisis"}),
            'plan':      forms.Textarea(attrs={'class': 'form-control', 'width': "100%", 'cols': "40", 'rows': "4", 'placeholder': "Plan"}),
            'folio':     forms.TextInput(attrs={'readonly': 'readonly'})
        }


    def clean_documento(self):
        print("entre a validar Documento Historia1 Form")
        documento = self.cleaned_data.get('documento')
        print (documento)
        id_tipo_doc = self.cleaned_data.get('id_tipo_doc')
        print(id_tipo_doc)
        id_tipo_doc1 = TiposDocumento.objects.get(nombre=id_tipo_doc)
        print(id_tipo_doc1.id)
        if Usuarios.objects.all().filter(id_tipo_doc=id_tipo_doc1.id).filter(nombre=documento).exists():
            print("ok Documento")
        else:
            raise forms.ValidationError('Documento de Usuario No existe . ')
            return documento
        return documento

    def clean_fecha(self):
        print("Entre Historia1View validar Fecha")
        fecha = self.cleaned_data.get('fecha')
        print(fecha)

        return fecha

    def clean_estado_folio(self):
        print("Entre Historia1View validar estado_folio")
        estado_folio = self.cleaned_data.get('estado_folio')
        print(estado_folio)

        return estado_folio

    def clean_id_especialidad(self):
        print("Entre Historia1View validar clean_id_especialidad")
        id_especialidad = self.cleaned_data.get('id_especialidad')
        print(id_especialidad)

        return id_especialidad

    def clean_id_medico(self):
        print("Entre Historia1View validar clean_id_medico")
        id_medico = self.cleaned_data.get('id_medico')
        print(id_medico)

        return id_medico

    def clean_motivo(self):
        print("Entre Historia1View validar motivo")
        motivo = self.cleaned_data.get('motivo')
        print(motivo)

        return motivo






class historiaExamenesForm(forms.ModelForm):

    class Meta:
        model = HistoriaExamenes

        id_tipo_doc = forms.ModelChoiceField(queryset=TiposDocumento.objects.all())
        documento = forms.IntegerField(label='No Documento')
        folio = forms.IntegerField(label='No Folio', disabled=True, initial=0)
        fecha = forms.DateTimeField()
        id_TipoExamen = forms.ModelChoiceField(queryset=TiposExamen.objects.all())
        id_examen = forms.ModelChoiceField(queryset=Examenes.objects.all())
        cantidad = forms.IntegerField(label='Cantidad')

        estado_folio = forms.CharField(label='Estado del Folio', disabled=True, initial='A', max_length=1)

        fields = '__all__'

    def clean_fecha(self):
        print ("Entre Fecha")
        fecha = self.cleaned_data.get('fecha')
        print(fecha)

        return fecha

    def clean_cantidad(self):
            print("Entre cantidad")
            cantidad = self.cleaned_data.get('cantidad')
            print(cantidad)

            return cantidad

    def clean_estado_folio(self):
        print("Entre esadofoklio")
        estado_folio = self.cleaned_data.get('estado_folio')
        print(estado_folio)

        return estado_folio


    def clean_id_examen(self):
        print("Entre id_examen")
        id_examen = self.cleaned_data.get('id_examen')
        print(id_examen)

        return id_examen

    def clean_id_TipoExamen(self):
        print("Entre id_TipoExamen")
        id_TipoExamen = self.cleaned_data.get('id_TipoExamen')
        print(id_TipoExamen)

        return id_TipoExamen








templates/historia1_form.html
{% extends "menu.html" %}
{% load static %}

{% block content %}


</br>
    </br>
<form action="" method="post" id="formHistoria" name="formHistoria">

    <div  class="col" id="mensajes"  name=mensajes" style=";font-size:15px;color:green;";>

       {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
        </div>
        <div class="form-control">
    <div class="form-group">
      <div class="row">
          <div class="col">

               {{ form.id_tipo_doc.label }}

                {{ form.id_tipo_doc }}
          </div>
            <div class="col">

                {{ form.documento.label }}

                {{ form.documento }}
          </div>
             <div class="col">
                  {{ form.folio.label }}
                {{ form.folio }}
          </div>
             <div class="col">


                {{ form.fecha.label }}
                  <input type="text" class="form-control" id="fecha" name="fecha" value={{ form.fecha }}>

             </div>

          <div class="col">
             {{ form.id_especialidad.label }}
                {{ form.id_especialidad }}
          </div>
            <div class="col">
                 {{ form.id_medico.label }}
                {{ form.id_medico }}
          </div>
      </div>

         <div class="row">

             <div class="col">
              {{ form.motivo.label }}
                {{ form.motivo }}
          </div>
              <div class="col">
                   <input type="button" id="btnmotivoSeñas" value="Motivo x Señas" />
                </div>
               <div class="col">
                  {{ form.objetivo.label }}
                {{ form.objetivo }}
          </div>
             <div class="col">
                   <input type="button" id="btnsubjetivoSeñas" value="Subjetivo x Señas" />
                </div>
             <div class="col">
                   {{ form.subjetivo.label }}
                {{ form.subjetivo }}
          </div>
      </div>

         <div class="row">
          <div class="col">
               {{ form.analisis.label }}
                {{ form.analisis }}
          </div>
            <div class="col">
                {{ form.plan.label }}
                {{ form.plan }}
          </div>
             <div class="col">
                {{ form.estado_folio.label }}
                {{ form.estado_folio }}
          </div>
       <div class="col">
                <input type="submit" value="Enviar" />
          </div>


      </div>

  </div>

</form>


{% endblock %}

templates/historia_form.html
{% extends "menu.html" %}
{% load static %}


{% load crispy_forms_tags %}

{% block content %}


</br>
</br>
<form action="" method="post" id="formHistoria" name="formHistoria">
        <input type="hidden" class="form-control" id="folio_oculto" name="folio_oculto" value="0" >
    <div  class="col" id="mensajes"  name=mensajes" style=";font-size:15px;color:green;";>
            {% if messages %}
        <ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    </div>
    <div class="form-control">
    <div class="form-group">

      <div class="row">
          <div class="col">

               {{ form.id_tipo_doc.label}}

                {{ form.id_tipo_doc}}
          </div>
            <div class="col">

                {{ form.documento.label }}

                {{ form.documento }}
          </div>
             <div class="col">
                  {{ form.folio.label }}
                {{ form.folio }}
          </div>
             <div class="col">


                {{ form.fecha.label }}
                  <input type="text" class="form-control" id="fecha" name="fecha" value={{ form.fecha }}>

             </div>

          <div class="col">
             {{ form.id_especialidad.label }}
                {{ form.id_especialidad }}
          </div>
            <div class="col">
                 {{ form.id_medico.label }}
                {{ form.id_medico }}
          </div>
      </div>

         <div class="row">

             <div class="col">
              {{ form.motivo.label }}
                {{ form.motivo }}
                 <div class=""row">
                         <div class="col">
                             <input type="button" id="btnmotivoSeñas" value="Señas Discapacitado" />
                             <input type="button" id="btnmotivoInvidente" value="Motivo Invidente" />
                             <input type="button" id="btnResmotivoInvidente" value="Respuesta Motivo" />
                        </div>
                 </div>

             </div>

               <div class="col">
                  {{ form.objetivo.label }}
                {{ form.objetivo }}

              </div>
            <div class="col">
                   {{ form.subjetivo.label }}
                {{ form.subjetivo }}
                  <div class=""row">
                         <div class="col">
                             <input type="button" id="btnsubjetivoSeñas" value="Señas Discapacitado" />
                             <input type="button" id="btnsubjetivoInvidente" value="Subjetivo Invidente" />
                             <input type="button" id="btnRessubjetivoInvidente" value="Respuesta Subjetivo" />
                        </div>
                  </div>


          </div>
      </div>
    <br>

         <div class="row">
          <div class="col">
               {{ form.analisis.label }}
                {{ form.analisis }}
          </div>
            <div class="col">
                {{ form.plan.label }}
                {{ form.plan }}
          </div>

       <div class="col">
                {{ form.estado_folio.label }}
                {{ form.estado_folio }}
                <input type="button" id= "btnFolio" value="Conseguir Folio" />
                <input type="submit" value=" Guardar " />
          </div>


      </div>

  </div>

</form>
</br>
<center><h5><b>EXAMENES PARACLINICOS A SOLICITAR</b></h5> </center>
</br>
<form action="" method="post" id="formClinicos" name="formClinicos">

<center>

    {{ form2.id_TipoExamen }}
    {{ form2.id_examen }}
    {{ form2.cantidad }}

      <input type="hidden" class="form-control" id="id_tipo_doc" name="id_tipo_doc" >
      <input type="hidden" class="form-control" id="documento" name="documento" >
      <input type="hidden" class="form-control" id="folio" name="folio" >
      <input type="hidden" class="form-control" id="fecha" name="fecha" >
      <input type="hidden" class="form-control" id="estado_folio" name="estado_folio" >


    <input type="button" id="btnAdicionarExamen" value="Adicionar" />

    </center>
<div class="container">

     <div class="scrollable">
           <center>
    <table  cellspacing="0" width="100%" class="table  table-fixed " id="Examenes" >

        <thead>
        <tr>

        <th style="width:40%">Tipo Examen</th>

        <th style="width:40%">Examen</th>
        <th style="width:10%">Cantidad</th>
         <th class="col-xs-1">  BORRAR </th>

            <th data-visible="false"></th>
            <th data-visible="false"></th>
            <th data-visible="false"></th>
            <th data-visible="false"></th>
            <th data-visible="false"></th>
            <th data-visible="false"></th>
            <th data-visible="false"></th>



        </tr>
        </thead>

        <tfoot>
        </tfoot>

    </table>
          </center>
     </div>

</div>


</form>

{% endblock %}

templates/home.html
{% extends "menu.html" %}
{% load static %}

{% block content %}
</br>
</br>
</br>

<form action="/camara" method="POST" id="formFoto" name="formFoto">
 <div class="form-group">
      <div class="row">
          <div class="col">

                    <label for="nombre">Nombre Fotografia</label>
                     <input type="text" class="form-control" id="nombre" name="nombre" placeholder="nombre">
          </div>
           <div  class="col" id="btnTomaFoto"  >
             <button type="button" class="btn btn-primary" id="btnTomaFoto"   >Tomar Fotografias</button>
           </div>
              <div  class="col" id="btnReproducir"  >
               <button type="button" class="btn btn-primary" id="btnReproducir"   >Reproducir Audio</button>
           </div>
        </div>

    </div>
        <div class="row">

               <div  class="col" id="mensajes"  name=mensajes" style=";font-size:25px;color:blue;";></div>


         </div>
</form>
{% endblock %}


templates/home1.html
{% extends "menu.html" %}
{% load static %}

{% block content %}

{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src={% static 'main.js' %} defer> </script>
    <title>
        {% block title %} {% endblock %}
    </title>
   <link rel="stylesheet" href="{% static 'js/popper.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">
  <link rel="stylesheet" href="{% static 'js/bootstrap.bundle.min.js' %}">

      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Custom js -->








</head>
<body>
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Navbar brand -->
    <a class="navbar-brand" href="#">Brand</a>

    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <!-- Navbar dropdown -->
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            Clinicos
          </a>
          <!-- Dropdown menu -->
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"
            >Disabled</a
          >
        </li>
      </ul>
      <!-- Left links -->

      <!-- Search form -->
      <form class="d-flex input-group w-auto">
        <input
          type="search"
          class="form-control"
          placeholder="Type query"
          aria-label="Search"
        />
        <button
          class="btn btn-outline-primary"
          type="button"
          data-mdb-ripple-color="dark"
        >
          Search
        </button>
      </form>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

{% block content  %}


{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/css/bootstrap-datetimepicker-standalone.css">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/js/bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">


<script>

var $ = jQuery;

 $(document).ready(function(){

   $('#id_id_TipoExamen').on('change', function (){
       //  alert("Entre Cambio tipo Examen");

        var id_TipoExamen =  document.getElementById("id_id_TipoExamen").value;
        var id_TipoExamen1 = id_TipoExamen;


		var datos={id_TipoExamen:id_TipoExamen1 };

		// alert("se va con");
	//	alert (JSON.stringify(datos));

  //      $.ajax({
  //          	   type: 'POST',
 //	               url: '/buscaExamenes/',
  //	               data: JSON.stringify(datos) ,
 //	      		success: function (respuesta2) {
 //	      		             var data = JSON.parse(respuesta2);
 //	      		             alert ("devuelve Estos Examenes");
 //	      		             alert(data.datos);



 //	      			      		},
 //	      		error: function (request, status, error) {
 //	      			alert(request.responseText);
 //	      			alert (error);
 //	      			$("#mensajes").html("Error Venta AJAX O RESPUESTA");
 	//      		},
 //	      		cache : false,
 //	      		contentType : false,
 //	      		processData: false,

 //	        });


  });

$(function () {
 var dateNow = new Date();

$('#fecha').datetimepicker({
 format: 'YYYY-MM-DD hh:mm:ss',
 defaultDate:dateNow
});
$("#fecha").data('DateTimePicker').setLocalDate(new Date(year, month, day, 00, 01));
  });




 $("#btnTomaFoto").click(function(){
        alert("Entre a Rutina Foto");

		var nombre = document.getElementById("nombre").value

  		 $.ajax({
	           url: '/camara',
	           type: 'GET',

	           data : {nombre:nombre},
	  		success: function (respuesta) {
                     var data = JSON.parse(respuesta);

	                      $("#mensajes").html(data.nombre + data.mensaje);
                    },
	   		    error: function (request, status, error) {

	   			    $("#mensajes").html(" !  Fotografia con error !");
	   	    	}

	     });
    });


    $("#btnmotivoSeñas").click(function(){
        alert("Entre a Motivo Señas");
        nombre="nada";



		 $.ajax({
	           url: '/motivoSeñas',
	           type: 'GET',

	           data : {nombre:nombre},
	  		success: function (respuesta) {
                     var data = JSON.parse(respuesta);
                             alert("llegue"),
                             alert(data.mensaje);

	                       document.formHistoria["motivo"].value =data.mensaje;
                    },
	   		    error: function (request, status, error) {

	   			    $("#mensajes").html(" !  Señas  con error !");
	   	    	}

	     });
    });

  $("#btnsubjetivoSeñas").click(function(){
        alert("Entre a Subjetivo Señas");
        nombre="nada";



		 $.ajax({
	           url: '/subjetivoSeñas',
	           type: 'GET',

	           data : {nombre:nombre},
	  		success: function (respuesta) {
                     var data = JSON.parse(respuesta);
                             alert("llegue"),
                             alert(data.mensaje);

	                       document.formHistoria["subjetivo"].value =data.mensaje;
                    },
	   		    error: function (request, status, error) {

	   			    $("#mensajes").html(" !  Señas  con error !");
	   	    	}

	     });
    });


$("#btnAdicionarExamen").click(function(){

     var id_tipo_doc    =  document.formHistoria["id_id_tipo_doc"].value
     var documento      =  document.formHistoria["id_documento"].value
     var folio          =  document.formHistoria["id_folio"].value
     var fecha          =  document.formHistoria["fecha"].value
     var estado_folio   =  document.formHistoria['id_estado_folio'].value

    var id_cantidad=document.getElementById("id_cantidad").value;
	var id_TipoExamen =  document.getElementById("id_id_TipoExamen").value;
	var comboTipoExamen = document.getElementById("id_id_TipoExamen");
	var tipoExamenNombre = comboTipoExamen.options[comboTipoExamen.selectedIndex].text;

	var id_examen =  document.getElementById("id_id_examen").value;
	var comboExamen = document.getElementById("id_id_examen");
	var ExamenNombre = comboExamen.options[comboExamen.selectedIndex].text;



		  var tds = '<tr>';

		  tds += '<td class="col-xs-2">' + tipoExamenNombre + '</td>';
		  tds += '<td class="col-xs-6">' + ExamenNombre + '</td>';
		  tds += '<td class="col-xs-6">' + id_cantidad + '</td>';
          tds += '<td class="col-xs-1"><a href="#">Delete</a></td>';


          tds += '<td  style="visibility: hidden">' + id_tipo_doc + '</td>';
		  tds += '<td  style="visibility: hidden">' + documento + '</td>';
		  tds += '<td  style="visibility: hidden" >' + folio + '</td>';
		  tds += '<td  style="visibility: hidden" >' + fecha + '</td>';
		  tds += '<td  style="visibility: hidden" >' + id_TipoExamen + '</td>';
		  tds += '<td  style="visibility: hidden" >' + id_examen + '</td>';
		  tds += '<td  style="visibility: hidden" >' + estado_folio + '</td>';



		tds += '</tr>';

		$("#Examenes").append(tds);


        datavta = $("#formClinicos").serialize();
     	datavta1 =  JSON.stringify(datavta);

	<!--	seriali.push(datavta1); -->


	//	envio.delete('id_tipo_doc');
	//	envio.delete('documento');
	//    envio.delete('folio');
	//	envio.delete('fecha');
	//	envio.delete('id_TipoExamen');
	//	envio.delete('id_examen');
	//	envio.delete('cantidad');
	//	envio.delete('estado_folio');

        envio.append('id_tipo_doc', id_tipo_doc );
        envio.append( 'documento', documento);
        envio.append('folio', document.getElementById("folio_oculto").value);
        envio.append('fecha', fecha);
        envio.append('id_TipoExamen' , id_TipoExamen);
        envio.append('id_examen' , id_examen);
        envio.append('cantidad' , id_cantidad);
        envio.append('estado_folio' , estado_folio);


             for (var valores in envio.values) {
                     console.log(valores);
             }


     //   var object = {};
       //     envio.forEach(function(value, key){
     //                 object[key] = value;
      //                  });

     //       var jsonEnvio = JSON.stringify(object);


        seriali1.push(envio);

        addAEvent();


   });

function addAEvent(){



			    $('#Examenes').unbind();


				  $('#Examenes').on('click','tr td', function(evt){



				        var target,valorSeleccionado;

				        var column_num = parseInt( $(this).index() + 1 ) ;

				        var row_num = parseInt( $(this).parent().index() + 1 );

				  	   target = $(evt.target);
						   valorSeleccionado = target.text();



					        if(column_num == 4)
					        	{

                                seriali.splice(row_num-3, 1);
					        	    $(this).closest('tr').remove();



  	                            event.preventDefault();

					        	}

				    });
		  			}



$("#btnResmotivoInvidente").click(function(){
        alert("Entre a Rutina Respuesta Motivo Paciente");


  		 $.ajax({
	           url: '/resMotivoInvidente',
	           type: 'GET',

	           data : {},
	  		success: function (respuesta) {
                     var data = JSON.parse(respuesta);


	                    document.getElementById("id_motivo").value = data.Respuesta;
                    },
	   		    error: function (request, status, error) {

	   			    $("#mensajes").html(" !  Reproduccion  con error !");
	   	    	}

	     });
    });



$("#btnmotivoInvidente").click(function(){
        alert("Entre a Rutina Reproducir Audio Motivo");

		var nombre = " Cual es el motivo de consulta "

  		 $.ajax({
	           url: '/motivoInvidente',
	           type: 'GET',

	           data : {nombre:nombre},
	  		success: function (respuesta) {
                     var data = JSON.parse(respuesta);

	                   //   $("#mensajes").html(data.nombre + data.mensaje);
                    },
	   		    error: function (request, status, error) {

	   			    $("#mensajes").html(" !  Reproduccion  con error !");
	   	    	}

	     });
    });



    $("#btnReproducir").click(function(){
        alert("Entre a Rutina Reproducir Audio");

		var nombre = document.getElementById("nombre").value

  		 $.ajax({
	           url: '/reproduceAudio',
	           type: 'GET',

	           data : {nombre:nombre},
	  		success: function (respuesta) {
                     var data = JSON.parse(respuesta);

	                      $("#mensajes").html(data.nombre + data.mensaje);
                    },
	   		    error: function (request, status, error) {

	   			    $("#mensajes").html(" !  Reproduccion  con error !");
	   	    	}

	     });
    });

 });
</script>
</body>

</html>


templates/manejoLuz.html
{% extends "menu.html" %}
{% load static %}

{% block content %}



Aqui a manipular Botones de Encender Apagar

<div class="row">

             <div class="col">

                       <input type="button" id="btnencender" value="Encender Luz" />
                       <input type="button" id="btnApagar" value="Apagar Luz" />
             </div>
</div>

{% endblock %}